### ISSUE TITLE
Create tutorial video for calibration and usage.

### ISSUE THREAD

**Issue by romanz** [romanz/amodem#12]

**Comment by romanz** [comment]
Estimate frequency drift during calibration

**Comment by romanz** [comment]
http://www.youtube.com/playlist?list=PLhSz1w57gk6K4lgK1k6Z_NBIAr9ujpEuN

**Comment by norill** [comment]
that playlist is set to private

**Comment by romanz** [comment]
Thanks for reporting this issue!
I have updated the permissions - it should work now.

**Comment by norill** [comment]
thank you
