### ISSUE TITLE
Problem between Android and PC version

### ISSUE THREAD

**Issue by bizzarrone** [romanz/amodem#17]
I tried to make make work the android app and the pc version on a debian but I could not.

**Comment by romanz** [comment]
Are you trying to send from Android to PC?
If so, can you please run the PC version with `-vv` flags and attach the resulting log?

**Comment by romanz** [comment]
BTW, which audio modem version are you using on Debian?

**Comment by romanz** [comment]
@bizzarrone , can you please send me the amodem receiving log?

**Comment by romanz** [comment]
@bizzarrone , I have no input regarding the issue.
