### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by mw44118** [romanz/amodem#20]
If I had two computers in a room, and one computer had speakers, and the other one had a microphone, could I use this library to send data from the first one to the second one?

**Comment by romanz** [comment]
Indeed :)

**Comment by mw44118** [comment]
Fantastic!  I'm going to use this in a computer programming class.

On Thu, Jan 14, 2016 at 4:24 PM, Roman Zeyde <notifications@github.com>
wrote:

> Indeed :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/romanz/amodem/issues/20#issuecomment-171784263>.
>



-- 
W. Matthew Wilson
partner
216 Software, LLC
matt@216software.com
http://216software.com

**Comment by romanz** [comment]
You're welcome!
