### ISSUE TITLE
question - comparable javascript implementation?

### ISSUE THREAD

**Issue by mvayngrib** [romanz/amodem#22]
awesome project! Do you know by any chance of a comparable JS implementation?

**Comment by romanz** [comment]
Thanks!
Long ago, I've written a simple sender (for the lowest bitrate) in JS here: https://github.com/romanz/amodem-js/
Unfortunately, it is probably out-of-date, so I'd recommend trying https://github.com/quiet/quiet-js.

**Comment by mvayngrib** [comment]
@romanz thanks! I actually found quiet-js a few hours after posting this issue, but thanks for the tip
