### ISSUE TITLE
Make sure the code works on Windows

### ISSUE THREAD

**Issue by romanz** [romanz/amodem#3]
find replacement for aplay and arecord.

**Comment by romanz** [comment]
https://github.com/elijahr/portaudio-ctypes

**Comment by romanz** [comment]
https://github.com/bastibe/PySoundCard/blob/master/win/portaudio32.dll

**Comment by romanz** [comment]
Use `-l` flag to load the DLL on Windows.

**Comment by RomanBelkov** [comment]
https://github.com/bastibe/PySoundCard/blob/master/win/portaudio32.dll -- this link is broken

**Comment by RomanBelkov** [comment]
Also, I've managed to set up and build portaudio, so I may provide the portaudio32.dll (after a couple of checks on other machines).

Moreover, It is not clear how one changes bitrate on Windows.

**Comment by romanz** [comment]
Thanks!
It seems that it has moved to https://github.com/bastibe/PySoundCard/blob/da8b4f057ff5ecfc3f1c7db491a9495654c9c6a0/_soundcard_data/portaudio32bit.dll.

**Comment by romanz** [comment]
Regarding the bitrate, I have used environment variable BITRATE.
IIRC, it should be specified via the SET command from the command-line, before running the modem:

    set BITRATE=16
