### ISSUE TITLE
Input/output from wav files

### ISSUE THREAD

**Issue by micahflee** [romanz/amodem#32]
It would be cool to have the option of reading and writing data to a wav file instead of an audio interface. (I'm having trouble getting either ALSA or PortAudio working with my setup, but also it seems like this could be useful for other reasons too.)

**Comment by romanz** [comment]
Thanks for opening this issue!
You can read/write PCM files using the `-i` and `-o` switches:
```
$ echo 123 | amodem send -o /tmp/file.pcm 
Sending 0.800 seconds of training audio
Starting modulation
Sent 0.004 kB @ 0.113 seconds
$ amodem recv -i /tmp/file.pcm
Waiting for carrier tone: 2.0 kHz
Carrier detected at ~150.0 ms @ 2.0 kHz
Carrier coherence: 100.000%
Carrier symbols amplitude : 1.000
Frequency error: 0.000 ppm
Starting demodulation
123
Received 0.004 kB @ 0.010 seconds = 0.402 kB/s
```

**Comment by romanz** [comment]
P.S.
The file has the following format is:

- Signed 16-bit 
- Little-endian
- 1 channel (mono)
- Sample rate depends on the [bitrate](https://github.com/romanz/amodem/blob/4846cdaf8f6ca6777f9decd009294433260ff124/amodem/config.py#L62)

**Comment by kromond** [comment]
Hi, I am trying to record the output from amodem, then decode at a later time.  I am having trouble making a pcm that is recognized by amodem.  Are there any details omitted here?

**Comment by kromond** [comment]
I realized I was not capturing the initial detection tone in my test.   Now that I have that in my recording, the pcm is recognized and carrier detected, but decoding fails, I guess from signal noise.

**Comment by romanz** [comment]
Thanks for letting me know, will take a look :)

**Comment by romanz** [comment]
I can suggest using SoX for converting raw PCM files into WAV files:
```
$ export BITRATE=8
$ echo 123 | amodem send -o audio.pcm
Audio OFDM MODEM v1.15.0: 8.0 kb/s (16-QAM x 2 carriers) Fs=8.0 kHz
Sending 0.800 seconds of training audio
Starting modulation
Sent 0.004 kB @ 0.015 seconds
$ sox --type=raw --bits=16 --channels=1 --encoding=signed-integer --rate=8000 --endian=little audio.pcm audio.wav
$ amodem recv -i audio.pcm -q
123
```
