### ISSUE TITLE
Adding a Python example

### ISSUE THREAD

**Issue by chyan26** [romanz/amodem#36]
Hi,

This is a amazing project.  I have installed the source code with pip.  However, the amodem does not work.  Would you please add a Python example program?

**Comment by romanz** [comment]
Thanks for the compliment :)

Could you run:
```bash
$ python -c "import amodem; print(amodem)"
```
and attach the results?

**Comment by PeppaCat** [comment]
> If the above code works, please try to run:
> 
> ```shell
> $ echo ABC | python3 -m amodem send -o- -vv | python3 -m amodem recv -i- -vv
> ```

Hi, I tried it on windows, but it says: Cannot open.
