### ISSUE TITLE
Add electrical engineering description

### ISSUE THREAD

**Issue by tchetagni** [romanz/amodem#38]
It's amazing what your have done. Thanks for it.
I still need to have an some detail about electronic schematics which lead to the code and also dependency schematic between python classes.
It will be very didactical to have a description from scratch to code, leading by circuit design documentation.

Once more, thanks for what you have already done.

**Comment by romanz** [comment]
Thanks a lot for the compliments!

I am planning to give a tech talk about this project, so I'll add a link to the slides (when they'll be ready).

**Comment by romanz** [comment]
-> #15
