### ISSUE TITLE
idea: add stealth mode, bypass microphone use

### ISSUE THREAD

**Issue by tiagotrs** [romanz/amodem#40]
would be interesting a stealth mode via ultrasonic waves.

a demo video from a implementation: https://www.youtube.com/watch?v=ZD8CNxYe5dk  
the full paper: https://arxiv.org/pdf/1803.03422.pdf

another interesting idea described in the paper is avoiding microphone by jack retasking the speaker.

**Comment by romanz** [comment]
Sounds interesting, thanks for the links!
Unfortunately, it will probably require to reduce the effective bitrate, so I would prefer to keep using the audible spectrum.
