### ISSUE TITLE
Please update reedsolo

### ISSUE THREAD

**Issue by lrq3000** [romanz/amodem#43]
Hello,

I am the current maintainer of [reedsolo](https://github.com/tomerfiliba/reedsolomon).

We have recently pushed major updates which increase speed and stability, but the API had to be changed.

If you are still using reedsolo, please ensure that you handle the 3 variables returned by reedsolo.

Before:

```python
>>> rsc = RSCodec(12)
>>> tampered_msg = b'heXlo worXd\xed%T\xc4\xfdX\x89\xf3\xa8\xaa'
>>> decoded_msg = rsc.decode(tampered_msg)
```

Now:

```python
>>> rsc = RSCodec(10)
>>> tampered_msg = b'heXlo worXd\xed%T\xc4\xfdX\x89\xf3\xa8\xaa'
>>> rmes, rmesecc, errata_pos = rsc.decode(tampered_msg)
```

As an alternative, you can setup your requirements.txt to require reedsolo<=0.3 to avoid the need to update.

**Comment by romanz** [comment]
Many thanks for the update!
Currently, this project doesn't use `reedsolo` package.
