### ISSUE TITLE
Does not work with BITRATE larger than 32 ?

### ISSUE THREAD

**Issue by zack77789** [romanz/amodem#47]
Tested with several bitrates, but did not work above 32  kb/s. Setting BITRATE=48 or 80 caused "ValueError: Invalid checksum".
I used 3.5mm jack as Line in receiving side and headphone out in sending side.

Also when calibrating it showed frequency change ?
![fc](https://user-images.githubusercontent.com/24804698/88774522-3ef39980-d18c-11ea-93d4-4fb58ef3838f.png)

**Comment by zack77789** [comment]
Solved!

**Comment by karkapur** [comment]
@zack77789 could you let us know how you solved it?
