### ISSUE TITLE
too weak signal

### ISSUE THREAD

**Issue by Easenguard** [romanz/amodem#81]
Hi there, I tried several calibrations, which all failed with "too weak sinal". 
Raising volume (to maximum) makes no difference.
Switching among bitrate configs result in all the same.
Wondering what else can be done :)

**Comment by ke4ahr** [comment]
Can you describe what your test environment is like and how you have things configured?

**Comment by romanz** [comment]
Calibration currently expects [the received signal root-mean-square power to be above 10% of the maximal value](https://github.com/romanz/amodem/blob/451551d37e966add9b59e6dbf66e155fe72cac34/amodem/calib.py#L70)  to be considered "non-weak", so I would suggest increasing the microphone gain (e.g. [as described here](https://www.howtogeek.com/700524/how-to-change-microphone-volume-in-windows-10/)).

I also suggest running `amodem recv -c -vv` which should log the actual measured values during the calibration.

**Comment by romanz** [comment]
Closing for now - @Easenguard please reopen if the issue persists.
